# Generated by Django 5.1.2 on 2024-11-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('party_affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('precinct_number', models.IntegerField(blank=True, null=True)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
