# Generated by Django 5.1.3 on 2024-11-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_comment_user_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators_plan',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accountz', to='project.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborators_trip',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account1', to='project.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborators_trip',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='project.account'),
        ),
    ]
