# Generated by Django 5.1.3 on 2024-11-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_collaborators_plan_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborators_plan',
            name='organizer',
        ),
    ]
