# Generated by Django 5.1.1 on 2024-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField()),
                ('last', models.TextField()),
                ('city', models.TextField()),
                ('email', models.TextField()),
                ('profile_img_url', models.TextField()),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
