# Generated by Django 5.1.1 on 2024-10-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_remove_statusmessage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mini_fb.profile'),
            preserve_default=False,
        ),
    ]
