# Generated by Django 5.1.2 on 2024-10-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
