# Generated by Django 5.1.2 on 2024-10-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_remove_profile_profile_img_url_profile_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('statusmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.statusmessage')),
            ],
        ),
    ]
